const SET_STATE = 'SET_STATE';
const RESET_STATE = 'RESET_STATE';
const RESET_RESULT_LIST = 'RESET_RESULT_LIST';

export default {
    SET_STATE: 'SET_STATE',
    RESET_STATE: 'RESET_STATE',
    RESET_RESULT_LIST: 'RESET_RESULT_LIST'
}